name: Build Devcontainer Images
on:
#   push:
#     branches:
#       - main
  workflow_dispatch: # Allow manual triggering

jobs:
  build-rootfs:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker
          uses: docker/setup-docker-action@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Set up Node.js
          uses: actions/setup-node@v4
          with:
            node-version: lts/*
        - run: npm install -g @devcontainers/cli

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Build Image
          run: |
            export image-name=sunshinecloud-java-devcontainers
            export image_version=latest
            devcontainer build --workspace-folder . --image-name sunshinecloud007/$image-name:$image_version 

        - name: Merge Docker Image
          run: |
            export src_image_name=sunshinecloud007/$image-name:$image_version
            export docker_tmp_name=temp1
            docker create -it -P --name $docker_tmp_name $src_image_name
            docker export $docker_tmp_name -o $docker_tmp_name.tar
            docker rm $docker_tmp_name
            docker rmi $src_image_name
            docker import $docker_tmp_name.tar $src_image_name
            rm $docker_tmp_name.tar
            docker images $src_image_name

        - name: Push Docker Image
          run: |
            docker push sunshinecloud007/$image-name:$image_version